name: "Update data"


on: # This workflow must be triggered on two conditions
        workflow_dispatch: # when we ask it manually (through the Actions UI or the GitHub API)

        push: # when we make a push to the main branch
            branches:
              - gh-pages
        
        schedule:
              - cron: '0 0 1 * *' # every first month's day

jobs: #this section contains the tasks / jobs that must be executed
        sync: # the job name
                runs-on: 'ubuntu-latest' # this job must run on a Ubuntu container
                steps:
                        - name: checkout on repository
                          uses: actions/checkout@main
                          with:
                             ref: ${{ github.read_ref }}
                             
                        - name: "Fetch latest formats.js file"
                          uses: actions/setup-node@v2
                          with:
                            node-version: '12'
                        - run: git clone https://github.com/smogon/pokemon-showdown.git    
                        - run: cd pokemon-showdown && npm i && node build
                        - run: cp .config-dist/formats.js ../temp/formats.js

                        - name: "Extract latest data"
                        - run: npm start
                        - name: Commit differences # commit if differences are tracked after updates (previous step)
                          uses: stefanzweifel/git-auto-commit-action@v4
                          with:
                              commit_message: Synchronization with Smogon's stats
                              commit_user_name: GitHub Actions Bot
                              commit_author: GitHub Action <actions@github.com>
                              skip_dirty_check: false
                              push_options:  --force